/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      maxWidth: {
        "3xl": "48rem",
      },
      colors: {
        ...{
          transparent: "transparent",
          current: "currentColor",
          black: "#000000",
          white: "#ffffff",
          gray: {
            50: "#f9fafb",
            100: "#f3f4f6",
            200: "#e5e7eb",
            300: "#d1d5db",
            400: "#9ca3af",
            500: "#6b7280",
            600: "#4b5563",
            700: "#374151",
            800: "#1f2937",
            900: "#111827",
          },
        },
        ...{
          primary: {
            50: "var(--color-primary-50)",
            100: "var(--color-primary-100)",
            200: "var(--color-primary-200)",
            300: "var(--color-primary-300)",
            400: "var(--color-primary-400)",
            500: "var(--color-primary-500)",
            600: "var(--color-primary-600)",
            700: "var(--color-primary-700)",
            800: "var(--color-primary-800)",
            900: "var(--color-primary-900)",
            DEFAULT: "var(--color-primary)",
            focus: "var(--color-primary-focus)",
            content: "var(--color-primary-content)",
          },
          secondary: {
            50: "var(--color-secondary-50)",
            100: "var(--color-secondary-100)",
            200: "var(--color-secondary-200)",
            300: "var(--color-secondary-300)",
            400: "var(--color-secondary-400)",
            500: "var(--color-secondary-500)",
            600: "var(--color-secondary-600)",
            700: "var(--color-secondary-700)",
            800: "var(--color-secondary-800)",
            900: "var(--color-secondary-900)",
            DEFAULT: "var(--color-secondary)",
            focus: "var(--color-secondary-focus)",
            content: "var(--color-secondary-content)",
          },
          accent: {
            50: "var(--color-accent-50)",
            100: "var(--color-accent-100)",
            200: "var(--color-accent-200)",
            300: "var(--color-accent-300)",
            400: "var(--color-accent-400)",
            500: "var(--color-accent-500)",
            600: "var(--color-accent-600)",
            700: "var(--color-accent-700)",
            800: "var(--color-accent-800)",
            900: "var(--color-accent-900)",
            DEFAULT: "var(--color-accent)",
            focus: "var(--color-accent-focus)",
            content: "var(--color-accent-content)",
          },
        },
        danger: "#ff4444",
        success: "#2ecc71",
        warning: "#f1c40f",
        error: {
          DEFAULT: "#dc2626",
          light: "#ef4444",
        },
      },
      backgroundColor: {
        dark: {
          DEFAULT: "#1a1a1a",
          lighter: "#2d2d2d",
        },
      },
      textColor: {
        dark: {
          DEFAULT: "#ffffff",
          muted: "#a0a0a0",
        },
      },
    },
  },
  plugins: [],
};
