name: Build & Deploy Spring Boot to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: SpringBoot-Server

    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions on server directory
        run: chmod -R u+rwX ./RecipeGPT2_Server

      - name: Write application.properties & service accounts
        working-directory: ./RecipeGPT2_Server
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
          FIREBASE_ADMIN_SA: ${{ secrets.FIREBASE_ADMIN_SA }}
          GCP_SPRINGBOOT_DEPLOYMENT_SA_KEY: ${{ secrets.GCP_SPRINGBOOT_DEPLOYMENT_SA_KEY }}
        run: |
          mkdir -p src/main/resources
          echo "$APPLICATION_PROPERTIES"            > src/main/resources/application.properties
          echo "$FIREBASE_ADMIN_SA"                  > src/main/resources/firebase-sa-key.json
          echo "$GCP_SPRINGBOOT_DEPLOYMENT_SA_KEY"   > src/main/resources/gcp-springboot-deployment-sa-key.json
          chmod 600 src/main/resources/*

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SPRINGBOOT_DEPLOYMENT_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          access_token_lifetime: 3600s

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker "${{ vars.GCP_LOCATION }}-docker.pkg.dev"

      # ─── Use system Maven ───
      - name: Set up Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run unit tests
        working-directory: ./RecipeGPT2_Server
        run: mvn --batch-mode test

      - name: Build JAR with system Maven (quiet)
        working-directory: ./RecipeGPT2_Server
        run: mvn -B -q clean package -DskipTests

      - name: Build and push Docker image (quiet)
        working-directory: ./RecipeGPT2_Server
        run: |
          IMAGE_URI="${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ secrets.CONTAINER_REPOSITORY }}/springboot:${{ github.sha }}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "Building image → $IMAGE_URI"
          docker build --quiet -t "$IMAGE_URI" .
          docker push "$IMAGE_URI" >/dev/null

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying $IMAGE_URI"
          gcloud run deploy springboot-service \
            --image "$IMAGE_URI" \
            --platform managed \
            --region "${{ vars.GCP_LOCATION }}" \
            --project "${{ vars.GCP_PROJECT_ID }}" \
            --service-account "${{ secrets.GCP_SPRINGBOOT_DEPLOYMENT_SA_NAME }}" \
            --set-env-vars "GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/firebase-admin.json" \
            --allow-unauthenticated
